package config;

import interfaces.IPiece;
import pieces.Amazon;
import pieces.Archbishop;
import pieces.Bishop;
import pieces.Centaur;
import pieces.Chancellor;
import pieces.Ferz;
import pieces.Grasshopper;
import pieces.King;
import pieces.Knight;
import pieces.Nightrider;
import pieces.NonRoyalKing;
import pieces.Nuke;
import pieces.Pawn;
import pieces.Queen;
import pieces.Rook;
import pieces.RoyalBishop;
import pieces.RoyalKnight;
import pieces.RoyalPawn;
import pieces.RoyalQueen;
import pieces.RoyalRook;
import pieces.Shield;
import pieces.Wazir;
import pieces.Zebra;

/** All concrete `PieceDef` rows; keep in sync with piece classes under `pieces/`. */
class PieceCatalogEntries {
    public static function build():Array<PieceDef> {
        var M = PieceCatalogMetrics;
        return [
            {
                id: "pawn",
                fenLower: "p",
                value: 1,
                factory: function(c:String):IPiece return new Pawn(c),
                engineFenLower: null,
                includeInFenDecode: true,
                toolbox: true,
                openingPhase: 2,
                pst: M.PST_PAWN,
                draw: M.DRAW_HEAVY,
                fallbackKingCentral: false,
                renderAs: null,
            },
            {
                id: "rook",
                fenLower: "r",
                value: 5,
                factory: function(c:String):IPiece return new Rook(c),
                engineFenLower: null,
                includeInFenDecode: true,
                toolbox: true,
                openingPhase: 24,
                pst: M.PST_ROOK,
                draw: M.DRAW_HEAVY,
                fallbackKingCentral: false,
                renderAs: null,
            },
            {
                id: "knight",
                fenLower: "n",
                value: 3,
                factory: function(c:String):IPiece return new Knight(c),
                engineFenLower: null,
                includeInFenDecode: true,
                toolbox: true,
                openingPhase: 12,
                pst: M.PST_KNIGHT,
                draw: M.DRAW_KNIGHT_MINOR,
                fallbackKingCentral: false,
                renderAs: null,
            },
            {
                id: "bishop",
                fenLower: "b",
                value: 3,
                factory: function(c:String):IPiece return new Bishop(c),
                engineFenLower: null,
                includeInFenDecode: true,
                toolbox: true,
                openingPhase: 12,
                pst: M.PST_BISHOP,
                draw: M.DRAW_BISHOP,
                fallbackKingCentral: false,
                renderAs: null,
            },
            {
                id: "queen",
                fenLower: "q",
                value: 9,
                factory: function(c:String):IPiece return new Queen(c),
                engineFenLower: null,
                includeInFenDecode: true,
                toolbox: true,
                openingPhase: 40,
                pst: M.PST_QUEEN,
                draw: M.DRAW_HEAVY,
                fallbackKingCentral: false,
                renderAs: null,
            },
            {
                id: "king",
                fenLower: "k",
                value: 1000,
                factory: function(c:String):IPiece return new King(c),
                engineFenLower: null,
                includeInFenDecode: true,
                toolbox: true,
                openingPhase: 0,
                pst: M.PST_KING_MG,
                draw: M.DRAW_ROYAL_KING,
                fallbackKingCentral: true,
                renderAs: null,
            },
            {
                id: "shield",
                fenLower: "h",
                value: 6,
                factory: function(c:String):IPiece return new Shield(c),
                engineFenLower: null,
                includeInFenDecode: true,
                toolbox: true,
                openingPhase: 24,
                pst: M.PST_KING_MG,
                draw: M.DRAW_DEFAULT_HEAVY,
                fallbackKingCentral: false,
                renderAs: null,
            },
            {
                id: "royalpawn",
                fenLower: "p",
                value: 500,
                factory: function(c:String):IPiece return new RoyalPawn(c),
                engineFenLower: "s",
                includeInFenDecode: false,
                toolbox: true,
                openingPhase: 24,
                pst: M.PST_PAWN,
                draw: M.DRAW_HEAVY,
                fallbackKingCentral: false,
                renderAs: null,
            },
            {
                id: "royalknight",
                fenLower: "x",
                value: 500,
                factory: function(c:String):IPiece return new RoyalKnight(c),
                engineFenLower: null,
                includeInFenDecode: true,
                toolbox: true,
                openingPhase: 24,
                pst: M.PST_KNIGHT_LIKE,
                draw: M.DRAW_KNIGHT_MINOR,
                fallbackKingCentral: false,
                renderAs: null,
            },
            {
                id: "royalqueen",
                fenLower: "y",
                value: 500,
                factory: function(c:String):IPiece return new RoyalQueen(c),
                engineFenLower: null,
                includeInFenDecode: true,
                toolbox: true,
                openingPhase: 48,
                pst: M.PST_QUEEN,
                draw: M.DRAW_HEAVY,
                fallbackKingCentral: false,
                renderAs: null,
            },
            {
                id: "royalrook",
                fenLower: "f",
                value: 500,
                factory: function(c:String):IPiece return new RoyalRook(c),
                engineFenLower: null,
                includeInFenDecode: true,
                toolbox: true,
                openingPhase: 32,
                pst: M.PST_ROOK,
                draw: M.DRAW_HEAVY,
                fallbackKingCentral: false,
                renderAs: null,
            },
            {
                id: "royalbishop",
                fenLower: "c",
                value: 500,
                factory: function(c:String):IPiece return new RoyalBishop(c),
                engineFenLower: null,
                includeInFenDecode: true,
                toolbox: true,
                openingPhase: 28,
                pst: M.PST_BISHOP,
                draw: M.DRAW_BISHOP,
                fallbackKingCentral: false,
                renderAs: null,
            },
            {
                id: "amazon",
                fenLower: "a",
                value: 12,
                factory: function(c:String):IPiece return new Amazon(c),
                engineFenLower: null,
                includeInFenDecode: true,
                toolbox: true,
                openingPhase: 48,
                pst: M.PST_AMAZON,
                draw: M.DRAW_HEAVY,
                fallbackKingCentral: false,
                renderAs: null,
            },
            {
                id: "chancellor",
                fenLower: "m",
                value: 10,
                factory: function(c:String):IPiece return new Chancellor(c),
                engineFenLower: null,
                includeInFenDecode: true,
                toolbox: true,
                openingPhase: 36,
                pst: M.PST_CHANCELLOR,
                draw: M.DRAW_HEAVY,
                fallbackKingCentral: false,
                renderAs: null,
            },
            {
                id: "archbishop",
                fenLower: "v",
                value: 8,
                factory: function(c:String):IPiece return new Archbishop(c),
                engineFenLower: null,
                includeInFenDecode: true,
                toolbox: true,
                openingPhase: 28,
                pst: M.PST_ARCHBISHOP,
                draw: M.DRAW_HEAVY,
                fallbackKingCentral: false,
                renderAs: null,
            },
            {
                id: "nightrider",
                fenLower: "d",
                value: 5,
                factory: function(c:String):IPiece return new Nightrider(c),
                engineFenLower: null,
                includeInFenDecode: true,
                toolbox: true,
                openingPhase: 20,
                pst: M.PST_KNIGHT_LIKE,
                draw: M.DRAW_HEAVY,
                fallbackKingCentral: false,
                renderAs: null,
            },
            {
                id: "zebra",
                fenLower: "z",
                value: 3,
                factory: function(c:String):IPiece return new Zebra(c),
                engineFenLower: null,
                includeInFenDecode: true,
                toolbox: true,
                openingPhase: 10,
                pst: M.PST_KNIGHT_LIKE,
                draw: M.DRAW_KNIGHT_MINOR,
                fallbackKingCentral: false,
                renderAs: null,
            },
            {
                id: "grasshopper",
                fenLower: "g",
                value: 4,
                factory: function(c:String):IPiece return new Grasshopper(c),
                engineFenLower: null,
                includeInFenDecode: true,
                toolbox: true,
                openingPhase: 12,
                pst: M.PST_GRASSHOPPER,
                draw: M.DRAW_HEAVY,
                fallbackKingCentral: false,
                renderAs: null,
            },
            {
                id: "centaur",
                fenLower: "t",
                value: 8,
                factory: function(c:String):IPiece return new Centaur(c),
                engineFenLower: null,
                includeInFenDecode: true,
                toolbox: true,
                openingPhase: 12,
                pst: M.PST_KNIGHT_LIKE,
                draw: M.DRAW_DEFAULT_HEAVY,
                fallbackKingCentral: false,
                renderAs: null,
            },
            {
                id: "nuke",
                fenLower: "w",
                value: 14,
                factory: function(c:String):IPiece return new Nuke(c),
                engineFenLower: null,
                includeInFenDecode: true,
                toolbox: true,
                openingPhase: 50,
                pst: M.PST_QUEEN,
                draw: M.DRAW_HEAVY,
                fallbackKingCentral: false,
                renderAs: null,
            },
            {
                id: "nonroyalking",
                fenLower: "u",
                value: 3,
                factory: function(c:String):IPiece return new NonRoyalKing(c),
                engineFenLower: null,
                includeInFenDecode: true,
                toolbox: true,
                openingPhase: 12,
                pst: M.PST_KNIGHT_LIKE,
                draw: M.DRAW_DEFAULT_HEAVY,
                fallbackKingCentral: false,
                renderAs: "king",
            },
            {
                id: "wazir",
                fenLower: "e",
                value: 2,
                factory: function(c:String):IPiece return new Wazir(c),
                engineFenLower: null,
                includeInFenDecode: true,
                toolbox: true,
                openingPhase: 8,
                pst: M.PST_KNIGHT_LIKE,
                draw: M.DRAW_DEFAULT_HEAVY,
                fallbackKingCentral: false,
                renderAs: null,
            },
            {
                id: "ferz",
                fenLower: "j",
                value: 2,
                factory: function(c:String):IPiece return new Ferz(c),
                engineFenLower: null,
                includeInFenDecode: true,
                toolbox: true,
                openingPhase: 8,
                pst: M.PST_KNIGHT_LIKE,
                draw: M.DRAW_DEFAULT_HEAVY,
                fallbackKingCentral: false,
                renderAs: null,
            }
        ];
    }
}
